name: Build and Test NGIAB TEEHR ARM

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-test-arm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and test ARM image
        uses: ./.github/actions/docker-test
        with:
          platform: linux/arm64
          image-tag: ngiab-teehr:test-arm
          buildcloud-endpoint: ${{ secrets.BUILDCLOUD_ENDPOINT }}