name: Build and Test NGIAB TEEHR x86

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-test-x86:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and test x86 image
        uses: ./.github/actions/docker-test
        with:
          platform: linux/amd64
          image-tag: ngiab-teehr:test-x86
          buildcloud-endpoint: ${{ secrets.BUILDCLOUD_ENDPOINT }}